### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thednp** [arian/CSSMatrix#10]
This code isn't working, see this [fiddle](https://jsfiddle.net/y0u68824/)

**Comment by arian** [comment]
It does work. It does not modify the object, but it returns a new object:

```js
var m = new CSSMatrix();
m = m.translate(150,200,300);
m = m.rotate(150,200,300);
console.log(m.toString());
// matrix3d(-0.4698463103929543, 0.8137976813493737, 0.34202014332566866, 0, -0.8355050358314171, -0.2849136355292076, -0.46984631039295416, 0, -0.28491363552920734, -0.5065151074942515, 0.8137976813493738, 0, 150, 200, 300, 1)
```

**Comment by thednp** [comment]
Nope, it's the same [check it](https://jsfiddle.net/y0u68824/1/)

**Comment by arian** [comment]
No, look closely at my code, then look at yours and read my comment.

```js
var m = new CSSMatrix().translate(150,200,300).rotate(150,200,300);
console.log(m.toString());
```

**Comment by thednp** [comment]
OK. Thanks you so much. 

Please copy paste this syntax on your project page so others don't waste time figuring out how it works.

Thanks again.
