### ISSUE TITLE
n00b question: can this code do "unmatrix"? 

### ISSUE THREAD

**Issue by thednp** [arian/CSSMatrix#8]
I need something to quickly build matrix / matrix3d or decompose them into pieces, can this code do all that? If yes, please write a 2-3 rows example.

Thanks

**Comment by arian** [comment]
Building the matrix can be done with the transform/rotate methods of course. Decomposing the matrix into components is something different. Here is some code for 2d matrices: https://github.com/kamicane/moofx/blob/master/lib/unmatrix2d.js

Search google for how to do that for 3d matrices, as I don't know that from the top of my head.

**Comment by thednp** [comment]
@arian thank you.
