### ISSUE TITLE
What about perspective for matrix3d and another script for matrix2d and more..

### ISSUE THREAD

**Issue by thednp** [arian/CSSMatrix#9]
I now understand what this code is for (I finally read it) and was thinking:
* can you provide a method similar to [this](https://github.com/start940315/matrix/blob/master/matrix.js#L425-L433) basically something like `rotate3d(rx,ry,rz)`
* can you also include method(s) for perspective, as this code does no 3D without specifying a parent perspective, and in many cases an element's perspective is more useful
* can you also make some similar `matrix` code for 2D operations?

Whoa that's alot of stuff :)

**Comment by arian** [comment]
- How is the current rotate different from rotate3d, you can do `m.rotate(rx, ry, rz)`?
- I guess?
- As 3d is an extension of 2d, you could create functions that use the 3d version in the correct way, yes. (something like `function rotate2d(m, r) { return m.rotate(0, 0, r); }`)

It's interesting to see extra methods and calculations, but I don't have the resources or interest to do this myself at this moment.

Besides that, the goal of this project was to implement the CSSMatrix spec, which it does, so it would be feature complete in that regard (except .invert() iirc).

**Comment by thednp** [comment]
Thanks for the answer, plain simple.

**Comment by thednp** [comment]
Hey I've read your code more and I like it best in all available here on Github. So yes, you have all methods including 2D `matrix` which is nice.
Look, I found [something on W3C](https://www.w3.org/TR/css3-3d-transforms/#recomposing-to-a-3d-matrix) that explains how to implement and what is the order, it says perspective comes first. So I cooked 2 new methods based on that code.

```javascript
  /**
   * The perspective method returns a new matrix which is this matrix post
   * multiplied by a perspective matrix containing the passed values. If the 
   * y and z components are undefined, a 0 value is used in its place. This matrix is not
   * modified.
   *
   * @param {number} x X component of the perspective value.
   * @param {number} y Y component of the perspective value.
   * @param {number=} z Z component of the perspective value.
   * @return {CSSMatrix} The result matrix
   */
  CSSMatrix.prototype.perspective = function(x, y, z){
    if (y == null) y = 0;
    if (z == null) z = 0;
    return CSSMatrix.multiply(this, CSSMatrix.Perspective(x, y, z));
  };
```
and
```javascript
  CSSMatrix.Perspective = function(x, y, z){
    var m = new CSSMatrix();
    m.m13 = x;
    m.m23 = y;
    m.m33 = z;
    return m;
  };
```

Can you please at least read this code if properly implemented into your code? I will put it to the test ASAP, I really need your OK :)
